name: AppendText

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
on:
#   pull_request:
#     branches: [ master ]
#     paths:
#     - '**.txt' # only take action when *.txt files change
  push:
    branches: [ master ]
    paths:
    - '**.txt' # only take action when *.txt files change
  workflow_dispatch:

# Alternative approach in https://dev.to/scienta/get-changed-files-in-github-actions-1p36

jobs:
  modifyfiles:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
           fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
          
#       - name: Get changed files
#         id: changed-files
#         uses: tj-actions/changed-files@v13
        
#       - name: List all changed files
#         run: |
#           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
#             echo "$file was changed"
#           done
          
      # Get list of files that have been changed
      - name: Get changed files
        id: changes
        run: |
          echo "all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.push.base.sha }} ${{ github.sha }} | xargs)" >> $GITHUB_OUTPUT
          echo "txt=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.push.base.sha }} ${{ github.sha }} | grep .txt$ | xargs)" >> $GITHUB_OUTPUT
      
      - name: Work with the list of modified files
        id: transform
#         if: ${{ steps.translator.outputs.has-new-translations }} == 'true'
        run: |
          echo "Modified file list: '${{ steps.changes.outputs.all }}'"
          echo "Modified text file list: '${{ steps.changes.outputs.txt }}'"
          echo "Calculating here the modified text file list: '$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }}  | grep .txt$ | xargs)'"
          input_files="${{ steps.changes.outputs.txt }}"
          echo $input_files
          for input_file in $input_files; do echo "Processing ${input_file}..."; echo "done_something=yes" >> $GITHUB_OUTPUT; sh ./scripts/base64encode.sh $input_file; done
          
      # Create the PR
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.10.1
        if: ${{ steps.transform.outputs.done_something }} == 'yes'
        with:
          title: 'Automatic processing of ${{ steps.changes.outputs.txt }}'
          body: 'Processed changed files ${{ steps.changes.outputs.txt }}'
