name: Test action

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  review_linter:
    runs-on: ubuntu-latest
    name: Review Checklist Linter
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: JSON Checklist Lint
        id: checklistlint
        uses: erjosito/review-checklist-lint@v0.1
        with:
          language: 'en'
      # Use the output from the `hello` step
      - name: Get the output
        run: echo "${{ steps.checklistlint.outputs.number_of_checklists }} checklists found..."
